/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package org.alliedoffsets

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())
  }

  def greeting(): String = "Hello, world!"
}
