/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package org.alliedoffsets

import org.alliedoffsets.service.ProjectDataService

object Main extends App with ProjectDataService {

  runService("127.0.0.1", 8080)
}
